config/routes.rb
Mydbs3::Application.routes.draw do

  resources :relaties

  resources :txes, :regdbs, :softdbs, :docdbs, :artdbs, :adresdbs, :accounts, :databases

  get "databases/index"
  root :to => "databases#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/adresdb.rb
class Adresdb < ActiveRecord::Base
  attr_accessible :relatie_id
  belongs_to :relatie
end

app/models/artdb.rb
class Artdb < ActiveRecord::Base
end

app/models/database.rb
class Database < ActiveRecord::Base
end

app/models/doccat.rb
class Doccat < ActiveRecord::Base
end

app/models/docdb.rb
class Docdb < ActiveRecord::Base
end

app/models/regdb.rb
class Regdb < ActiveRecord::Base
end

app/models/relatie.rb
class Relatie < ActiveRecord::Base
   attr_accessible :naam
   has_many :adresdbs
end

app/models/rubrieken.rb
class Rubrieken < ActiveRecord::Base
end

app/models/softcat.rb
class Softcat < ActiveRecord::Base
end

app/models/softdb.rb
class Softdb < ActiveRecord::Base
end

app/models/tijdschriften.rb
class Tijdschriften < ActiveRecord::Base
end

app/models/tx.rb
class Tx < ActiveRecord::Base
end

app/controllers/regdbs_controller.rb
class RegdbsController < ApplicationController
  # GET /regdbs
  # GET /regdbs.xml
  def index
    @search   = Regdb.search(params[:search])
    @search.meta_sort ||= 'Naam.asc' 
    @regdbs   = @search.all.paginate(:page => params[:page], :per_page => 18)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @regdbs }
    end
  end

  # GET /regdbs/1
  # GET /regdbs/1.xml
  def show
    @regdb = Regdb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @regdb }
    end
  end

  # GET /regdbs/new
  # GET /regdbs/new.xml
  def new
    @regdb = Regdb.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @regdb }
    end
  end

  # GET /regdbs/1/edit
  def edit
    @regdb = Regdb.find(params[:id])
  end

  # POST /regdbs
  # POST /regdbs.xml
  def create
    @regdb = Regdb.new(params[:regdb])

    respond_to do |format|
      if @regdb.save
        format.html { redirect_to(@regdb, :notice => 'Regdb was successfully created.') }
        format.xml  { render :xml => @regdb, :status => :created, :location => @regdb }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @regdb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /regdbs/1
  # PUT /regdbs/1.xml
  def update
    @regdb = Regdb.find(params[:id])

    respond_to do |format|
      if @regdb.update_attributes(params[:regdb])
        format.html { redirect_to(@regdb, :notice => 'Regdb was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @regdb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /regdbs/1
  # DELETE /regdbs/1.xml
  def destroy
    @regdb = Regdb.find(params[:id])
    @regdb.destroy

    respond_to do |format|
      format.html { redirect_to(regdbs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/adresdbs_helper.rb
module AdresdbsHelper
end

app/helpers/artdbs_helper.rb
module ArtdbsHelper
end

app/helpers/databases_helper.rb
module DatabasesHelper
end

app/helpers/docdbs_helper.rb
module DocdbsHelper
end

app/helpers/regdbs_helper.rb
module RegdbsHelper
end

app/helpers/relaties_helper.rb
module RelatiesHelper
end

app/helpers/softdbs_helper.rb
module SoftdbsHelper
end

app/helpers/txes_helper.rb
module TxesHelper
end

app/views/regdbs/_form.html.erb
<%= form_for(@regdb) do |f| %>
  <% if @regdb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regdb.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @regdb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table>
  <tr>
     <td><%= f.label :product %><br />
         <%= f.text_field :product %></td>
     <td>
        <%= f.label :expires %><br />
        <%= f.text_field :expires, :size => 10 %>
     </td>
  <tr>
  <td>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </td> 
  <tr></tr>
  <tr>
	<td><%= f.label :login %><br />
        <%= f.text_field :login, :size => 10 %>
    </td>
    <td>
       <%= f.label :passwd %><br />
       <%= f.text_field :passwd, :size => 5 %>
    </td>
  </tr>
  <tr>
    <td><%= f.label :notes %><br />
        <%= f.text_area :notes %>
    </td>
  </tr>
</table>

<p>
    <%= f.submit 'Toevoegen' %>
</p>
<% end %>

app/views/regdbs/edit.html.erb
<h2>Wijzig Registratie</h2>  

<%= render :partial => 'form' %> 

<%= link_to "Verwijder", @regdb, :confirm => 'Zeker weten?', :method => :delete %> |
<%= link_to 'Terug', regdbs_path %>

app/views/regdbs/index.html.erb
<h2>Registraties</h2>

<table class='sortable' border='1'>
  <tr bgcolor='green'>
    <th width="150">Product</th>
    <th>Verloopt</th>
    <th width='250'>Url</th>
    <th width='150'>Login</th>
    <th>Wachtwoord</th> 
  </tr>

<% @regdbs.each do |regdb| %>
<tr class="<%= cycle("even", "odd") %>">
    <td><%= link_to regdb.product, regdb %></td>
    <td><%=h regdb.expires %></td>
    <td><%=h regdb.url %></td>
    <td><%=h regdb.login %></td>
    <td><%=h regdb.passwd %></td> 
  </tr>
<% end %>
</table>   

<p><%= will_paginate @regdbs %></p>
<br />

<%= link_to 'Registratie toevoegen', new_regdb_path %>

app/views/regdbs/new.html.erb
<h2>Nieuwe Registratie</h2>

<%= render 'form' %>

<%= link_to 'Terug', regdbs_path %>

app/views/regdbs/show.html.erb
<h2>Registratie informatie</h2>
<p
<table width="50%">
  <tr>
     <td><b>Product:</b></td>
     <td><%=h @regdb.product %></td>
  </tr>

  <tr>
     <td><b>Verloopt:</b></td>
     <td><%=h @regdb.expires %></td>
  </tr>

  <tr>
     <td><b>Url:</b></td>
     <td><%=h @regdb.url %></td>
  </tr>

  <tr>
     <td><b>Login:</b></td>
     <td><%=h @regdb.login %></td>
  </tr>

  <tr>
     <td><b>Wachtwoord:</b></td>
     <td><%=h @regdb.passwd %></td>
  </tr>

	<tr>
     <td><b>Notities:</b></td>
     <td><%=h @regdb.notes %></td>
  </tr>
</table>

<p>
<%= link_to 'Wijzig', edit_regdb_path(@regdb) %> |
<%= link_to "Verwijder", @regdb, :confirm => 'Zeker weten?', :method => :delete %> |
<%= link_to 'Terug', regdbs_path %>