config/routes.rb
Mydbs3::Application.routes.draw do

  resources :relaties

  resources :txes, :regdbs, :softdbs, :docdbs, :artdbs, :adresdbs, :accounts, :databases

  get "databases/index"
  root :to => "databases#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/adresdb.rb
class Adresdb < ActiveRecord::Base
  attr_accessible :relatie_id
  belongs_to :relatie
end

app/models/artdb.rb
class Artdb < ActiveRecord::Base
end

app/models/database.rb
class Database < ActiveRecord::Base
end

app/models/doccat.rb
class Doccat < ActiveRecord::Base
end

app/models/docdb.rb
class Docdb < ActiveRecord::Base
end

app/models/regdb.rb
class Regdb < ActiveRecord::Base
end

app/models/relatie.rb
class Relatie < ActiveRecord::Base
   attr_accessible :naam
   has_many :adresdbs
end

app/models/rubrieken.rb
class Rubrieken < ActiveRecord::Base
end

app/models/softcat.rb
class Softcat < ActiveRecord::Base
end

app/models/softdb.rb
class Softdb < ActiveRecord::Base
end

app/models/tijdschriften.rb
class Tijdschriften < ActiveRecord::Base
end

app/models/tx.rb
class Tx < ActiveRecord::Base
end

app/controllers/relaties_controller.rb
class RelatiesController < ApplicationController
  # GET /relaties
  # GET /relaties.xml
  def index
    @relaties = Relatie.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @relaties }
    end
  end

  # GET /relaties/1
  # GET /relaties/1.xml
  def show
    @relaty = Relatie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @relaty }
    end
  end

  # GET /relaties/new
  # GET /relaties/new.xml
  def new
    @relaty = Relatie.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @relaty }
    end
  end

  # GET /relaties/1/edit
  def edit
    @relaty = Relatie.find(params[:id])
  end

  # POST /relaties
  # POST /relaties.xml
  def create
    @relaty = Relatie.new(params[:relaty])

    respond_to do |format|
      if @relaty.save
        format.html { redirect_to(@relaty, :notice => 'Relatie was successfully created.') }
        format.xml  { render :xml => @relaty, :status => :created, :location => @relaty }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @relaty.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /relaties/1
  # PUT /relaties/1.xml
  def update
    @relaty = Relatie.find(params[:id])

    respond_to do |format|
      if @relaty.update_attributes(params[:relaty])
        format.html { redirect_to(@relaty, :notice => 'Relatie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @relaty.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /relaties/1
  # DELETE /relaties/1.xml
  def destroy
    @relaty = Relatie.find(params[:id])
    @relaty.destroy

    respond_to do |format|
      format.html { redirect_to(relaties_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/adresdbs_helper.rb
module AdresdbsHelper
end

app/helpers/artdbs_helper.rb
module ArtdbsHelper
end

app/helpers/docdbs_helper.rb
module DocdbsHelper
end

app/helpers/regdbs_helper.rb
module RegdbsHelper
end

app/helpers/relaties_helper.rb
module RelatiesHelper
end

app/helpers/softdbs_helper.rb
module SoftdbsHelper
end

app/helpers/txes_helper.rb
module TxesHelper
end

app/views/relaties/_form.html.erb
<%= simple_form_for(@relatie) do |f| %>
  <% if @relatie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relatie.errors.count, "error") %> prohibited this relatie from being saved:</h2>

      <ul>
      <% @relatie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
    <%= f.input :naam %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/relaties/edit.html.erb
<h1>Editing relaty</h1>

<%= render 'form' %>

<%= link_to 'Show', @relaty %> |
<%= link_to 'Back', relaties_path %>

app/views/relaties/index.html.erb
<h1>Listing relaties</h1>

<table>
  <tr>
    <th>Naam</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @relaties.each do |relaty| %>
  <tr>
    <td><%= relaty.naam %></td>
    <td><%= link_to 'Show', relaty %></td>
    <td><%= link_to 'Edit', edit_relaty_path(relaty) %></td>
    <td><%= link_to 'Destroy', relaty, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Relatie', new_relaty_path %>

app/views/relaties/new.html.erb
<h1>New relaty</h1>

<%= render 'form' %>

<%= link_to 'Back', relaties_path %>

app/views/relaties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Naam:</b>
  <%= @relaty.naam %>
</p>


<%= link_to 'Edit', edit_relaty_path(@relaty) %> |
<%= link_to 'Back', relaties_path %>