config/routes.rb
Mydbs3::Application.routes.draw do

  resources :relaties

  resources :txes, :regdbs, :softdbs, :docdbs, :artdbs, :adresdbs, :accounts, :databases

  get "databases/index"
  root :to => "databases#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/adresdb.rb
class Adresdb < ActiveRecord::Base
  attr_accessible :relatie_id
  belongs_to :relatie
end

app/models/artdb.rb
class Artdb < ActiveRecord::Base
end

app/models/database.rb
class Database < ActiveRecord::Base
end

app/models/doccat.rb
class Doccat < ActiveRecord::Base
end

app/models/docdb.rb
class Docdb < ActiveRecord::Base
end

app/models/regdb.rb
class Regdb < ActiveRecord::Base
end

app/models/relatie.rb
class Relatie < ActiveRecord::Base
   attr_accessible :naam
   has_many :adresdbs
end

app/models/rubrieken.rb
class Rubrieken < ActiveRecord::Base
end

app/models/softcat.rb
class Softcat < ActiveRecord::Base
end

app/models/softdb.rb
class Softdb < ActiveRecord::Base
end

app/models/tijdschriften.rb
class Tijdschriften < ActiveRecord::Base
end

app/models/tx.rb
class Tx < ActiveRecord::Base
end

app/controllers/softdbs_controller.rb
class SoftdbsController < ApplicationController
  # GET /softdbs
  # GET /softdbs.xml
  def index
#    @softdbs = Softdb.all
    @search     = Softdb.search(params[:search])
    @search.meta_sort ||= 'fdate.desc' 
    @softdbs   = @search.all.paginate(:page => params[:page], :per_page => 21)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @softdbs }
    end
  end

  # GET /softdbs/1
  # GET /softdbs/1.xml
  def show
    @softdb = Softdb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @softdb }
    end
  end

  # GET /softdbs/new
  # GET /softdbs/new.xml
  def new
    @softdb = Softdb.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @softdb }
    end
  end

  # GET /softdbs/1/edit
  def edit
    @softdb = Softdb.find(params[:id])
  end

  # POST /softdbs
  # POST /softdbs.xml
  def create
    @softdb = Softdb.new(params[:softdb])

    respond_to do |format|
      if @softdb.save
        format.html { redirect_to(@softdb, :notice => 'Softdb was successfully created.') }
        format.xml  { render :xml => @softdb, :status => :created, :location => @softdb }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @softdb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /softdbs/1
  # PUT /softdbs/1.xml
  def update
    @softdb = Softdb.find(params[:id])

    respond_to do |format|
      if @softdb.update_attributes(params[:softdb])
        format.html { redirect_to(@softdb, :notice => 'Softdb was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @softdb.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /softdbs/1
  # DELETE /softdbs/1.xml
  def destroy
    @softdb = Softdb.find(params[:id])
    @softdb.destroy

    respond_to do |format|
      format.html { redirect_to(softdbs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/adresdbs_helper.rb
module AdresdbsHelper
end

app/helpers/artdbs_helper.rb
module ArtdbsHelper
end

app/helpers/databases_helper.rb
module DatabasesHelper
end

app/helpers/docdbs_helper.rb
module DocdbsHelper
end

app/helpers/regdbs_helper.rb
module RegdbsHelper
end

app/helpers/relaties_helper.rb
module RelatiesHelper
end

app/helpers/softdbs_helper.rb
module SoftdbsHelper
end

app/helpers/txes_helper.rb
module TxesHelper
end

app/views/softdbs/_form.html.erb
<%= form_for @softdb, :html => {:name => 'Software'} do |f| %> 
  <% if @softdb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@softdb.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @softdb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table width="80%">
  <tr>
     <td><%= f.label 'Bestand:' %><br />
         <%= f.text_field :fname %></td>
     <td><%= f.label 'Grootte:' %><br />
         <%= f.text_field :fsize %></td>
     <td><%= f.label 'Datum:' %><br />
         <%= f.text_field :fdate %></td>
  </tr>
  <tr>
     <td><%= f.label 'Volume:' %><br />
         <%= f.text_field :fvol %></td>
     <td><%= f.label 'Hidden:' %><br />
         <%= f.text_field :fhide %></td>
     <td><%= f.label 'Soort:' %><br />
         <%= f.select :fcat, ["INFO","SYSUTL","COMM","TXTUTL","MISC","BACKUP","WWW", "DRIVER","PATCH","VTOC"], :include_blank => true %></td>
     </tr>
  <tr>
    <td><%= f.label 'Omschrijving:' %><br />
        <%= f.text_field :fdesc %></td>
  </tr>
</table>
<p>
    <%= f.submit 'Aanmaken' %>
</p>
<% end %>

app/views/softdbs/edit.html.erb
<h2>Wijzig software item</h2>

<%= render :partial => 'form' %>


<%= link_to "Terug", softdbs_path %>
<%= link_to "Verwijder", @softdb, :confirm => 'Zeker weten?', :method => :delete %>

app/views/softdbs/index.html.erb
<h2>Software Overzicht</h2>

<%= form_for @search do |f| %>
  <p>
    <%= f.label :fname_contains, "Bestand:" %>
    <%= f.text_field :fname_contains, :size => 20 %>
    <%= f.label :fcat_contains, "Soort:" %>
    <%= f.text_field :fcat_contains, :size => 8 %>
    <%= f.label :fvol_contains, "Volume:" %>
    <%= f.text_field :fvol_contains, :size => 8 %>

    <%= f.submit "Zoek", :name => nil %>
  </p>
<% end %>

<table class='sortable' border='1'>
  <tr bgcolor='green'>
    <th width='250'>Bestand</th>
    <th align='right'>Grootte</th>
    <th>Datum</th>
    <th>Volume</th>
    <th>Soort</th>
    <th align='left' width='400'>Beschrijving</th>
  </tr>

<% @softdbs.each do |softdb| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%= link_to softdb.fname, softdb %></td>
    <td align='right'><%=h softdb.fsize %></td>
    <td><%=h softdb.fdate %></td>
    <td><%=h softdb.fvol %></td>
    <td><%=h softdb.fcat %></td>
    <td><%=h softdb.fdesc %></td>

<% end %>
</table>

<p>  
  <%= link_to 'Software toevoegen', new_softdb_path %>       
</p>    

  <%= will_paginate @softdbs %>  
<br />

app/views/softdbs/new.html.erb
<h2>Software toevoegen</h2>

<%= render 'form' %>

<%= link_to 'Terug', softdbs_path %>

app/views/softdbs/show.html.erb
<h2>Software Overzicht</h2>
<p>
<table width="50%">
  <tr>
     <td><b>Bestand:</b></td>
     <td><%=h @softdb.fname %></td>
  </tr>

  <tr>
     <td><b>Grootte:</b></td>
     <td><%=h @softdb.fsize %></td>
  </tr>

  <tr>
     <td><b>Datum:</b></td>
     <td><%=h @softdb.fdate %></td>
  </tr>

  <tr>
     <td><b>Volume:</b></td>
     <td><%=h @softdb.fvol %></td>
  </tr>

  <tr>
     <td><b>Hidden:</b></td>
     <td><%=h @softdb.fhide %></td>
  </tr>

  <tr>
     <td><b>Soort:</b></td>
     <td><%=h @softdb.fcat %></td>
  </tr>

  <tr>
     <td><b>Omschrijving:</b></td>
     <td><%=h @softdb.fdesc %></td>
  </tr>
</table>

<p>
<%= link_to 'Wijzig', edit_softdb_path(@softdb) %> |
<%= link_to "Verwijder", @softdb, :confirm => 'Zeker weten?', :method => :delete %> |
<%= link_to "Terug", softdbs_path %>
</p>